# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Dowloads\test_sub.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# from PyQt5 import QtCore, QtGui, QtWidgets


from PyQt5 import QtCore, QtGui, QtWidgets

import pickle
from joblib import dump, load
import pandas as pd
from sklearn.linear_model import LinearRegression as lr, LinearRegression


class Ui_MainWindow(object):

    data = []
    labels = []
    text_edits = []
    def setup_ui(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 339)

        font = QtGui.QFont()
        font.setPointSize(9)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.te_sex = QtWidgets.QTextEdit(self.centralwidget)
        self.te_sex.setGeometry(QtCore.QRect(60, 20, 81, 31))
        self.te_sex.setObjectName("te_sex")
        self.text_edits.append(self.te_sex)

        self.btn_predict = QtWidgets.QPushButton(self.centralwidget)
        self.btn_predict.setGeometry(QtCore.QRect(140, 240, 75, 23))
        self.btn_predict.setObjectName("btn_predict")
        self.btn_predict.clicked.connect(self.get_data_from_label)

        self.l_sex = QtWidgets.QLabel(self.centralwidget)
        self.l_sex.setGeometry(QtCore.QRect(20, 30, 47, 13))
        self.l_sex.setFont(font)
        self.l_sex.setObjectName("l_sex")

        self.te_PAT = QtWidgets.QTextEdit(self.centralwidget)
        self.te_PAT.setGeometry(QtCore.QRect(60, 70, 81, 31))
        self.te_PAT.setObjectName("te_PAT")
        self.text_edits.append(self.te_PAT)

        self.l_has_PAT = QtWidgets.QLabel(self.centralwidget)
        self.l_has_PAT.setGeometry(QtCore.QRect(20, 80, 47, 13))
        self.l_has_PAT.setFont(font)
        self.l_has_PAT.setObjectName("l_has_PAT")

        self.l_height = QtWidgets.QLabel(self.centralwidget)
        self.l_height.setGeometry(QtCore.QRect(20, 190, 47, 13))
        self.l_height.setFont(font)
        self.l_height.setObjectName("l_height")

        self.te_age = QtWidgets.QTextEdit(self.centralwidget)
        self.te_age.setGeometry(QtCore.QRect(60, 130, 81, 31))
        self.te_age.setObjectName("te_age")
        self.text_edits.append(self.te_age)

        self.te_height = QtWidgets.QTextEdit(self.centralwidget)
        self.te_height.setGeometry(QtCore.QRect(60, 180, 81, 31))
        self.te_height.setObjectName("te_height")
        self.text_edits.append(self.te_height)

        self.l_age = QtWidgets.QLabel(self.centralwidget)
        self.l_age.setGeometry(QtCore.QRect(0, 140, 47, 13))
        self.l_age.setFont(font)
        self.l_age.setObjectName("l_age")

        self.l_talia = QtWidgets.QLabel(self.centralwidget)
        self.l_talia.setGeometry(QtCore.QRect(200, 80, 47, 13))
        self.l_talia.setFont(font)
        self.l_talia.setObjectName("l_talia")

        self.te_talia = QtWidgets.QTextEdit(self.centralwidget)
        self.te_talia.setGeometry(QtCore.QRect(240, 70, 81, 31))
        self.te_talia.setObjectName("te_talia")
        self.text_edits.append(self.te_talia)

        self.te_weight = QtWidgets.QTextEdit(self.centralwidget)
        self.te_weight.setGeometry(QtCore.QRect(240, 20, 81, 31))
        self.te_weight.setObjectName("te_weight")
        self.text_edits.append(self.te_weight)

        self.l_weight = QtWidgets.QLabel(self.centralwidget)
        self.l_weight.setGeometry(QtCore.QRect(200, 30, 47, 13))
        self.l_weight.setFont(font)
        self.l_weight.setObjectName("l_weight")

        self.l_DAD = QtWidgets.QLabel(self.centralwidget)
        self.l_DAD.setGeometry(QtCore.QRect(200, 190, 47, 13))
        self.l_DAD.setFont(font)
        self.l_DAD.setObjectName("l_DAD")

        self.te_DAD = QtWidgets.QTextEdit(self.centralwidget)
        self.te_DAD.setGeometry(QtCore.QRect(240, 180, 81, 31))
        self.te_DAD.setObjectName("te_DAD")
        self.text_edits.append(self.te_DAD)

        self.te_SAD = QtWidgets.QTextEdit(self.centralwidget)
        self.te_SAD.setGeometry(QtCore.QRect(240, 130, 81, 31))
        self.te_SAD.setObjectName("te_SAD")
        self.text_edits.append(self.te_SAD)

        self.l_SAD = QtWidgets.QLabel(self.centralwidget)
        self.l_SAD.setGeometry(QtCore.QRect(200, 140, 47, 13))
        self.l_SAD.setFont(font)
        self.l_SAD.setObjectName("l_SAD")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_predict.setText(_translate("MainWindow", "Предсказать"))
        self.l_sex.setText(_translate("MainWindow", "Пол"))
        self.l_has_PAT.setText(_translate("MainWindow", "ПЭТ?"))
        self.l_height.setText(_translate("MainWindow", "Рост"))
        self.l_age.setText(_translate("MainWindow", "Возраст"))
        self.l_talia.setText(_translate("MainWindow", "Талия"))
        self.l_weight.setText(_translate("MainWindow", "Вес"))
        self.l_DAD.setText(_translate("MainWindow", "ДАД"))
        self.l_SAD.setText(_translate("MainWindow", "САД"))

    def get_data_from_label(self):
        self.data = []
        for text_edit in self.text_edits:
            self.data.append(float(text_edit.toPlainText()))
        # print(*self.data)
        Pkl_Filename = "Pickle_RL_Model.pkl"
        with open(Pkl_Filename, 'rb') as file:
            Pickled_LR_Model = pickle.load(file)
        # print(Pickled_LR_Model)
        pd_array = pd.DataFrame(self.data)
        pd_array = pd_array.transpose()
        result = Pickled_LR_Model.predict(pd_array)
        print("Принимая субатрамин вы похудеете на " + str(*result) + "% в течении 3 месяцев")
        # return self.data

if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setup_ui(main_window)
    main_window.show()
    # new_data = ui.get_data_from_label(main_window)
    print("Я тут")
    sys.exit(app.exec_())