# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Dowloads\test_sub.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    data = []
    labels = []
    text_edits = []

    def setup_ui(self, main_window):

        main_window.setObjectName("MainWindow")
        main_window.resize(700, 569)

        font = QtGui.QFont()
        font.setPointSize(8)

        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")

        self.te_age = QtWidgets.QTextEdit(self.centralwidget)
        self.te_age.setGeometry(QtCore.QRect(80, 10, 104, 31))
        self.te_age.setObjectName("te_age")

        self.l_age = QtWidgets.QLabel(self.centralwidget)
        self.l_age.setGeometry(QtCore.QRect(0, 10, 71, 31))
        self.l_age.setFont(font)
        self.l_age.setObjectName("l_age")

        self.l_height = QtWidgets.QLabel(self.centralwidget)
        self.l_height.setGeometry(QtCore.QRect(0, 60, 61, 31))
        self.l_height.setFont(font)
        self.l_height.setObjectName("l_height")

        self.te_height = QtWidgets.QTextEdit(self.centralwidget)
        self.te_height.setGeometry(QtCore.QRect(80, 60, 104, 31))
        self.te_height.setObjectName("te_height")

        self.l_weight = QtWidgets.QLabel(self.centralwidget)
        self.l_weight.setGeometry(QtCore.QRect(0, 120, 61, 31))
        self.l_weight.setFont(font)
        self.l_weight.setObjectName("l_weight")

        self.te_weight = QtWidgets.QTextEdit(self.centralwidget)
        self.te_weight.setGeometry(QtCore.QRect(80, 120, 104, 31))
        self.te_weight.setObjectName("te_weight")

        self.l_OB = QtWidgets.QLabel(self.centralwidget)
        self.l_OB.setGeometry(QtCore.QRect(0, 220, 61, 31))
        self.l_OB.setFont(font)
        self.l_OB.setObjectName("l_OB")

        self.l_OT = QtWidgets.QLabel(self.centralwidget)
        self.l_OT.setGeometry(QtCore.QRect(0, 170, 61, 31))
        self.l_OT.setFont(font)
        self.l_OT.setObjectName("l_OT")

        self.l_IMT = QtWidgets.QLabel(self.centralwidget)
        self.l_IMT.setGeometry(QtCore.QRect(0, 280, 61, 31))
        self.l_IMT.setFont(font)
        self.l_IMT.setObjectName("l_IMT")

        self.te_IMT = QtWidgets.QTextEdit(self.centralwidget)
        self.te_IMT.setGeometry(QtCore.QRect(80, 280, 104, 31))
        self.te_IMT.setObjectName("te_IMT")

        self.te_OB = QtWidgets.QTextEdit(self.centralwidget)
        self.te_OB.setGeometry(QtCore.QRect(80, 220, 104, 31))
        self.te_OB.setObjectName("te_OB")

        self.te_OT = QtWidgets.QTextEdit(self.centralwidget)
        self.te_OT.setGeometry(QtCore.QRect(80, 170, 104, 31))
        self.te_OT.setObjectName("te_OT")

        self.l_DAD = QtWidgets.QLabel(self.centralwidget)
        self.l_DAD.setGeometry(QtCore.QRect(0, 380, 61, 31))
        self.l_DAD.setFont(font)
        self.l_DAD.setObjectName("l_DAD")

        self.l_SAD = QtWidgets.QLabel(self.centralwidget)
        self.l_SAD.setGeometry(QtCore.QRect(0, 330, 61, 31))
        self.l_SAD.setFont(font)
        self.l_SAD.setObjectName("l_SAD")

        self.l_glucose = QtWidgets.QLabel(self.centralwidget)
        self.l_glucose.setGeometry(QtCore.QRect(0, 440, 61, 31))
        self.l_glucose.setFont(font)
        self.l_glucose.setObjectName("l_glucose")

        self.te_glucose = QtWidgets.QTextEdit(self.centralwidget)
        self.te_glucose.setGeometry(QtCore.QRect(80, 440, 104, 31))
        self.te_glucose.setObjectName("te_glucose")

        self.te_DAD = QtWidgets.QTextEdit(self.centralwidget)
        self.te_DAD.setGeometry(QtCore.QRect(80, 380, 104, 31))
        self.te_DAD.setObjectName("te_DAD")

        self.te_SAD = QtWidgets.QTextEdit(self.centralwidget)
        self.te_SAD.setGeometry(QtCore.QRect(80, 330, 104, 31))
        self.te_SAD.setObjectName("te_SAD")

        self.te_LPVP = QtWidgets.QTextEdit(self.centralwidget)
        self.te_LPVP.setGeometry(QtCore.QRect(290, 220, 104, 31))
        self.te_LPVP.setObjectName("te_LPVP")

        self.te_OHS = QtWidgets.QTextEdit(self.centralwidget)
        self.te_OHS.setGeometry(QtCore.QRect(290, 170, 104, 31))
        self.te_OHS.setObjectName("te_OHS")

        self.l_B = QtWidgets.QLabel(self.centralwidget)
        self.l_B.setGeometry(QtCore.QRect(210, 120, 61, 31))
        self.l_B.setFont(font)
        self.l_B.setObjectName("l_B")

        self.te_IR = QtWidgets.QTextEdit(self.centralwidget)
        self.te_IR.setGeometry(QtCore.QRect(290, 60, 104, 31))
        self.te_IR.setObjectName("te_IR")

        self.l_LPONP = QtWidgets.QLabel(self.centralwidget)
        self.l_LPONP.setGeometry(QtCore.QRect(210, 330, 61, 31))
        self.l_LPONP.setFont(font)
        self.l_LPONP.setObjectName("l_LPONP")

        self.te_insulin = QtWidgets.QTextEdit(self.centralwidget)
        self.te_insulin.setGeometry(QtCore.QRect(290, 10, 104, 31))
        self.te_insulin.setObjectName("te_insulin")

        self.l_TG = QtWidgets.QLabel(self.centralwidget)
        self.l_TG.setGeometry(QtCore.QRect(210, 380, 61, 31))
        self.l_TG.setFont(font)
        self.l_TG.setObjectName("l_TG")

        self.l_KA = QtWidgets.QLabel(self.centralwidget)
        self.l_KA.setGeometry(QtCore.QRect(210, 440, 61, 31))
        self.l_KA.setFont(font)
        self.l_KA.setObjectName("l_KA")

        self.l_LPVP = QtWidgets.QLabel(self.centralwidget)
        self.l_LPVP.setGeometry(QtCore.QRect(210, 220, 61, 31))
        self.l_LPVP.setFont(font)
        self.l_LPVP.setObjectName("l_LPVP")

        self.te_KA = QtWidgets.QTextEdit(self.centralwidget)
        self.te_KA.setGeometry(QtCore.QRect(290, 440, 104, 31))
        self.te_KA.setObjectName("te_KA")

        self.te_LPONP = QtWidgets.QTextEdit(self.centralwidget)
        self.te_LPONP.setGeometry(QtCore.QRect(290, 330, 104, 31))
        self.te_LPONP.setObjectName("te_LPONP")

        self.l_IR = QtWidgets.QLabel(self.centralwidget)
        self.l_IR.setGeometry(QtCore.QRect(210, 60, 61, 31))
        self.l_IR.setFont(font)
        self.l_IR.setObjectName("l_IR")

        self.l_insulin = QtWidgets.QLabel(self.centralwidget)
        self.l_insulin.setGeometry(QtCore.QRect(210, 10, 61, 31))
        self.l_insulin.setFont(font)
        self.l_insulin.setObjectName("l_insulin")

        self.te_B = QtWidgets.QTextEdit(self.centralwidget)
        self.te_B.setGeometry(QtCore.QRect(290, 120, 104, 31))
        self.te_B.setObjectName("te_B")

        self.te_TG = QtWidgets.QTextEdit(self.centralwidget)
        self.te_TG.setGeometry(QtCore.QRect(290, 380, 104, 31))
        self.te_TG.setObjectName("te_TG")

        self.l_LPNP = QtWidgets.QLabel(self.centralwidget)
        self.l_LPNP.setGeometry(QtCore.QRect(210, 280, 61, 31))
        self.l_LPNP.setFont(font)
        self.l_LPNP.setObjectName("l_LPNP")

        self.te_LPNP = QtWidgets.QTextEdit(self.centralwidget)
        self.te_LPNP.setGeometry(QtCore.QRect(290, 280, 104, 31))
        self.te_LPNP.setObjectName("te_LPNP")

        self.l_OHS = QtWidgets.QLabel(self.centralwidget)
        self.l_OHS.setGeometry(QtCore.QRect(210, 170, 61, 31))
        self.l_OHS.setFont(font)
        self.l_OHS.setObjectName("l_OHS")

        self.l_sex = QtWidgets.QLabel(self.centralwidget)
        self.l_sex.setGeometry(QtCore.QRect(410, 60, 61, 31))
        self.l_sex.setFont(font)
        self.l_sex.setObjectName("l_sex")

        self.te_sex = QtWidgets.QTextEdit(self.centralwidget)
        self.te_sex.setGeometry(QtCore.QRect(490, 60, 104, 31))
        self.te_sex.setObjectName("te_sex")

        self.l_deg_obesity = QtWidgets.QLabel(self.centralwidget)
        self.l_deg_obesity.setGeometry(QtCore.QRect(400, 170, 91, 41))
        self.l_deg_obesity.setFont(font)
        self.l_deg_obesity.setObjectName("l_deg_obesity")

        self.te_has_PAT = QtWidgets.QTextEdit(self.centralwidget)
        self.te_has_PAT.setGeometry(QtCore.QRect(490, 120, 104, 31))
        self.te_has_PAT.setObjectName("te_has_PAT")

        self.l_hypertension = QtWidgets.QLabel(self.centralwidget)
        self.l_hypertension.setGeometry(QtCore.QRect(410, 280, 61, 31))
        self.l_hypertension.setFont(font)
        self.l_hypertension.setObjectName("l_hypertension")

        self.te_deg_obesity = QtWidgets.QTextEdit(self.centralwidget)
        self.te_deg_obesity.setGeometry(QtCore.QRect(490, 170, 104, 31))
        self.te_deg_obesity.setObjectName("te_deg_obesity")

        self.te_dyslipidemia = QtWidgets.QTextEdit(self.centralwidget)
        self.te_dyslipidemia.setGeometry(QtCore.QRect(490, 330, 104, 31))
        self.te_dyslipidemia.setObjectName("te_dyslipidemia")

        self.te_SRB = QtWidgets.QTextEdit(self.centralwidget)
        self.te_SRB.setGeometry(QtCore.QRect(490, 10, 104, 31))
        self.te_SRB.setObjectName("te_SRB")

        self.l_NTG = QtWidgets.QLabel(self.centralwidget)
        self.l_NTG.setGeometry(QtCore.QRect(410, 230, 61, 31))
        self.l_NTG.setFont(font)
        self.l_NTG.setObjectName("l_NTG")

        self.te_NTG = QtWidgets.QTextEdit(self.centralwidget)
        self.te_NTG.setGeometry(QtCore.QRect(490, 230, 104, 31))
        self.te_NTG.setObjectName("te_NTG")

        self.te_hypertension = QtWidgets.QTextEdit(self.centralwidget)
        self.te_hypertension.setGeometry(QtCore.QRect(490, 280, 104, 31))
        self.te_hypertension.setObjectName("te_hypertension")

        self.l_dyslipidemia = QtWidgets.QLabel(self.centralwidget)
        self.l_dyslipidemia.setGeometry(QtCore.QRect(410, 330, 61, 31))
        self.l_dyslipidemia.setFont(font)
        self.l_dyslipidemia.setObjectName("l_dyslipidemia")

        self.l_has_PAT = QtWidgets.QLabel(self.centralwidget)
        self.l_has_PAT.setGeometry(QtCore.QRect(410, 120, 61, 31))
        self.l_has_PAT.setFont(font)
        self.l_has_PAT.setObjectName("l_has_PAT")

        self.l_SRB = QtWidgets.QLabel(self.centralwidget)
        self.l_SRB.setGeometry(QtCore.QRect(410, 10, 61, 31))
        self.l_SRB.setFont(font)
        self.l_SRB.setObjectName("l_SRB")

        self.l_MZO = QtWidgets.QLabel(self.centralwidget)
        self.l_MZO.setGeometry(QtCore.QRect(410, 380, 61, 31))
        self.l_MZO.setFont(font)
        self.l_MZO.setObjectName("l_MZO")

        self.te_MZO = QtWidgets.QTextEdit(self.centralwidget)
        self.te_MZO.setGeometry(QtCore.QRect(490, 380, 104, 31))
        self.te_MZO.setObjectName("te_MZO")

        self.btn_calc = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calc.setGeometry(QtCore.QRect(500, 450, 75, 23))
        self.btn_calc.setObjectName("btn_calc")
        self.btn_calc.clicked.connect(self.get_data_from_label)

        main_window.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.l_age.setText(_translate("MainWindow", "Возраст"))
        self.l_height.setText(_translate("MainWindow", "Рост"))
        self.l_weight.setText(_translate("MainWindow", "Вес"))
        self.l_OB.setText(_translate("MainWindow", "ОБ"))
        self.l_OT.setText(_translate("MainWindow", "ОТ"))
        self.l_IMT.setText(_translate("MainWindow", "ИМТ"))
        self.l_DAD.setText(_translate("MainWindow", "ДАД"))
        self.l_SAD.setText(_translate("MainWindow", "САД"))
        self.l_glucose.setText(_translate("MainWindow", "Глюкоза"))
        self.l_B.setText(_translate("MainWindow", "B"))
        self.l_LPONP.setText(_translate("MainWindow", "ЛПОНП"))
        self.l_TG.setText(_translate("MainWindow", "ТГ"))
        self.l_KA.setText(_translate("MainWindow", "КА"))
        self.l_LPVP.setText(_translate("MainWindow", "ЛПВП"))
        self.l_IR.setText(_translate("MainWindow", "IR"))
        self.l_insulin.setText(_translate("MainWindow", "Инсулин"))
        self.l_LPNP.setText(_translate("MainWindow", "ЛПНП"))
        self.l_OHS.setText(_translate("MainWindow", "ОХС"))
        self.l_sex.setText(_translate("MainWindow", "Пол"))
        self.l_deg_obesity.setText(_translate("MainWindow", "Степ ожир"))
        self.l_hypertension.setText(_translate("MainWindow", "Гиперт"))
        self.l_NTG.setText(_translate("MainWindow", "НТГ"))
        self.l_dyslipidemia.setText(_translate("MainWindow", "Дислип"))
        self.l_has_PAT.setText(_translate("MainWindow", "ПЭТ?"))
        self.l_SRB.setText(_translate("MainWindow", "С-РБ"))
        self.l_MZO.setText(_translate("MainWindow", "МЗО"))
        self.btn_calc.setText(_translate("MainWindow", "Посчитать"))

    def get_data_from_label(self):
        self.data = []
        r = self.te_age.toPlainText()
        self.data.append(r)
        print(*self.data)
        return self.data


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setup_ui(main_window)
    main_window.show()
#    new_data = ui.get_data_from_label(main_window)
    print("Я тут")
    sys.exit(app.exec_())